# Generated by Django 6.0 on 2025-12-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.displaytype')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.process')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayMachineProcessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.displaytype')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
            options={
                'unique_together': {('display', 'machine', 'process')},
            },
        ),
    ]
