# Generated by Django 6.0 on 2026-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('schema_version', models.CharField(blank=True, default='', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cliente', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('numero_display', models.CharField(blank=True, default='', max_length=100)),
                ('maquinario', models.CharField(max_length=255)),
                ('processo', models.CharField(max_length=255)),
                ('data_producao', models.CharField(blank=True, default='', max_length=20)),
                ('operadores', models.TextField(blank=True, default='')),
                ('numero_operadores', models.PositiveIntegerField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, default='', max_length=10)),
                ('hora_fim', models.CharField(blank=True, default='', max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('pecas_mortas', models.PositiveIntegerField(default=0)),
                ('quantidade_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registro de producao',
                'verbose_name_plural': 'Registros de producao',
                'ordering': ('-timestamp', '-id'),
            },
        ),
    ]
