# Generated by Django 6.0 on 2026-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='import_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='source_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64),
        ),
    ]
