# Generated by Django 6.0 on 2026-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productionentry_import_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
